.TH "D:/Mes Donnees/GitHub/VERSAO_VegaMonitor/__init__.py" 3 "Jeudi 4 Août 2016" "VERSAO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Mes Donnees/GitHub/VERSAO_VegaMonitor/__init__.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI " \fBVERSAO_VegaMonitor\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "def \fBVERSAO_VegaMonitor\&.classFactory\fP (iface)"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VERSAO à partir du code source\&.
