.TH "FORM_CLASS" 3 "Jeudi 4 Août 2016" "VERSAO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FORM_CLASS \- 
.SH SYNOPSIS
.br
.PP
.PP
Dérivée par \fBVERSAO_VegaMonitor\&.metrique_phenologique_dialog\&.metriquePhenologiqueDialog\fP, et \fBVERSAO_VegaMonitor\&.VERSAO_VegaMonitor_dialog\&.VERSAOVegaMonitorDialog\fP\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VERSAO à partir du code source\&.
