.TH "D:/Mes Donnees/GitHub/VERSAO_P2I/function_data_raster.py" 3 "Mercredi 3 Août 2016" "VERSAO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Mes Donnees/GitHub/VERSAO_P2I/function_data_raster.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI " \fBVERSAO_P2I\&.function_data_raster\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "def \fBVERSAO_P2I\&.function_data_raster\&.open_data\fP (filename)"
.br
.ti -1c
.RI "def \fBVERSAO_P2I\&.function_data_raster\&.write_data\fP (outname, im, GeoTransform, Projection)"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VERSAO à partir du code source\&.
