.TH "D:/Mes Donnees/GitHub/VERSAO_P2I/metriquePheno.py" 3 "Mercredi 3 Août 2016" "VERSAO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Mes Donnees/GitHub/VERSAO_P2I/metriquePheno.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI " \fBVERSAO_P2I\&.metriquePheno\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "def \fBVERSAO_P2I\&.metriquePheno\&.metrique_pheno_greenbrown\fP (ndvi=sp\&.empty, methode='trs', seuil1=\-1, seuil2=\-1)"
.br
.ti -1c
.RI "def \fBVERSAO_P2I\&.metriquePheno\&.metrique_pheno_vito\fP (ndvi=sp\&.empty, seuil1=0\&.25, seuil2=0\&.75)"
.br
.ti -1c
.RI "def \fBVERSAO_P2I\&.metriquePheno\&.metrique_pheno_derivative\fP (ndvi=sp\&.empty)"
.br
.ti -1c
.RI "def \fBVERSAO_P2I\&.metriquePheno\&.metrique_pheno_param\fP (inNdvi=sp\&.empty, inSos=0, inEos=0, inIndMax=0)"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VERSAO à partir du code source\&.
