.TH "D:/Mes Donnees/GitHub/VERSAO_P2I/resources.py" 3 "Jeudi 30 Juin 2016" "VERSAO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Mes Donnees/GitHub/VERSAO_P2I/resources.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI " \fBVERSAO_P2I\&.resources\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "def \fBVERSAO_P2I\&.resources\&.qInitResources\fP ()"
.br
.ti -1c
.RI "def \fBVERSAO_P2I\&.resources\&.qCleanupResources\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBVERSAO_P2I\&.resources\&.qt_resource_data\fP"
.br
.ti -1c
.RI "string \fBVERSAO_P2I\&.resources\&.qt_resource_name\fP"
.br
.ti -1c
.RI "string \fBVERSAO_P2I\&.resources\&.qt_resource_struct\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VERSAO à partir du code source\&.
