.TH "VERSAO_VegaMonitor.VERSAO_VegaMonitor_dialog.VERSAOVegaMonitorDialog" 3 "Jeudi 4 Août 2016" "VERSAO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VERSAO_VegaMonitor.VERSAO_VegaMonitor_dialog.VERSAOVegaMonitorDialog \- 
.SH SYNOPSIS
.br
.PP
.PP
Est dérivée de QDialog, et \fBFORM_CLASS\fP\&.
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, parent=None)"
.br
.in -1c
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "def VERSAO_VegaMonitor\&.VERSAO_VegaMonitor_dialog\&.VERSAOVegaMonitorDialog\&.__init__ ( self,  parent = \fCNone\fP)"

.PP
.nf
Constructor.
.fi
.PP
 

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VERSAO à partir du code source\&.
