.TH "VERSAO_P2I.metriquePheno" 3 "Jeudi 30 Juin 2016" "VERSAO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VERSAO_P2I.metriquePheno \- 
.SH SYNOPSIS
.br
.PP
.SS "Fonctions"

.in +1c
.ti -1c
.RI "def \fBmetrique_pheno_greenbrown\fP (ndvi=sp\&.empty, methode='trs', seuil1=\-1, seuil2=\-1)"
.br
.ti -1c
.RI "def \fBmetrique_pheno_vito\fP (ndvi=sp\&.empty, seuil1=0\&.3, seuil2=0\&.75)"
.br
.ti -1c
.RI "def \fBmetrique_pheno_Tang\fP (ndvi=sp\&.empty, seuil1=\-1, seuil2=\-1)"
.br
.ti -1c
.RI "def \fBmetrique_pheno_param\fP (inNdvi=sp\&.empty, inSos=0, inEos=0, inIndMax=0)"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "def VERSAO_P2I\&.metriquePheno\&.metrique_pheno_greenbrown ( ndvi = \fCsp\&.empty\fP,  methode = \fC'trs'\fP,  seuil1 = \fC\-1\fP,  seuil2 = \fC\-1\fP)"

.PP
.nf
Ce script permet d'identifier les dates de debut de saison,
de fin de saison à partir du NDVI.
il est inspiré du script R:https://github.com/rforge/greenbrown/blob/master/pkg/greenbrown/R/PhenoTrs.R
Entrée:
    ndvi: les données de ndvi
    seuil1: correspond au seuil autour du quel on pense trouver le debut de la vegetation
    seuil2: correspond au seuil autour du quel on pense trouver la sénéscence
    ndvi : correspond à l'evolution DU NDVI pour un pixel sur une année
    methode: correspond à la methode à utiliser pour l'estimation
Sortie:
    une liste contenant le sos, eos, los, indMin n(indice du min),indMax (indice du max), ndvi min et ndvi max

.fi
.PP
 
.SS "def VERSAO_P2I\&.metriquePheno\&.metrique_pheno_param ( inNdvi = \fCsp\&.empty\fP,  inSos = \fC0\fP,  inEos = \fC0\fP,  inIndMax = \fC0\fP)"

.PP
.nf
Ce script a pour objectif de calculer differentes metriques phenologique 
à partir du NDVI

Entree:
inNDVI: le NDVI
inSos:  la seizaine correspondant au debut de saison
inEos:  la seizaine correspondant à la fin de saison
inIndMax: indice de la valeur maximale du NDVI (floraison)

Sortie:
outListe: une liste contenant l'ensemble des métriques phénologiques calculées
.fi
.PP
 
.SS "def VERSAO_P2I\&.metriquePheno\&.metrique_pheno_Tang ( ndvi = \fCsp\&.empty\fP,  seuil1 = \fC\-1\fP,  seuil2 = \fC\-1\fP)"

.PP
.nf
Ce script permet d'identifier les dates de debut de saison,
de fin de saison à partir du NDVI. Elle est aussi appelé methode à seuil variable
En utilisant l'option par défaut le seuil utilisé correspond à celui conseillé dans :
Variability and Climate Change Trend in Vegetation Phenology of Recent Decades in the Greater Khingan
Mountain Area, Northeastern China
 Huan Tang , Zhenwang Li , Zhiliang Zhu , Baorui Chen , Baohui Zhang  and Xiaoping Xin ,
 

seuil1: correspond au seuil autour du quel on pense trouver le debut de la croissance de la végétation
seuil1: correspond au seuil autour du quel on pense trouver la fin de la croissance de la végétation

ndvi : correspond à l'evolution DU NDVI pour un pixel sur une année
.fi
.PP
 
.SS "def VERSAO_P2I\&.metriquePheno\&.metrique_pheno_vito ( ndvi = \fCsp\&.empty\fP,  seuil1 = \fC0\&.3\fP,  seuil2 = \fC0\&.75\fP)"

.PP
.nf
Ce script permet d'identifier les dates de debut de saison, de fin de saison à partir du NDVI à partir d'un seuil.
Entrée:
    ndvi: les données de ndvi
    seuil1: correspond au seuil autour du quel on pense trouver le debut de la vegetation
    seuil2: correspond au seuil autour du quel on pense trouver la sénéscence
    ndvi : correspond à l'evolution DU NDVI pour un pixel sur une année
    methode: correspond à la methode à utiliser pour l'estimation
Sortie:
    une liste contenant le sos, eos, los, indMin n(indice du min),indMax (indice du max), ndvi min et ndvi max

.fi
.PP
 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VERSAO à partir du code source\&.
