.TH "D:/Mes Donnees/GitHub/VERSAO_P2I/wh_filter.py" 3 "Mercredi 3 Août 2016" "VERSAO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Mes Donnees/GitHub/VERSAO_P2I/wh_filter.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI " \fBVERSAO_P2I\&.wh_filter\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "def \fBVERSAO_P2I\&.wh_filter\&.whfilter\fP (a, weights=None, lamb=1600, p=3)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBVERSAO_P2I\&.wh_filter\&.x\fP = np\&.arange(200);"
.br
.ti -1c
.RI "int \fBVERSAO_P2I\&.wh_filter\&.y\fP = x**2"
.br
.ti -1c
.RI "\fBVERSAO_P2I\&.wh_filter\&.yp\fP = whfilter(y,lamb=0\&.01,weights=1\&./(1+np\&.abs(y)));"
.br
.ti -1c
.RI "\fBVERSAO_P2I\&.wh_filter\&.label\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VERSAO à partir du code source\&.
