.TH "D:/Mes Donnees/GitHub/VERSAO_P2I/clip.py" 3 "Jeudi 30 Juin 2016" "VERSAO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Mes Donnees/GitHub/VERSAO_P2I/clip.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI " \fBVERSAO_P2I\&.clip\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "def \fBVERSAO_P2I\&.clip\&.world2Pixel\fP (geoMatrix, x, y)"
.br
.ti -1c
.RI "def \fBVERSAO_P2I\&.clip\&.clipRaster\fP (srcImage, G, P, shapefile_path)"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VERSAO à partir du code source\&.
