.TH "D:/Mes Donnees/GitHub/VERSAO_VegaMonitor/my_aggregate.py" 3 "Mercredi 3 Août 2016" "VERSAO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Mes Donnees/GitHub/VERSAO_VegaMonitor/my_aggregate.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI " \fBVERSAO_VegaMonitor\&.my_aggregate\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "def \fBVERSAO_VegaMonitor\&.my_aggregate\&.view_as_blocks\fP (arr_in, block_shape)"
.br
.ti -1c
.RI "def \fBVERSAO_VegaMonitor\&.my_aggregate\&.view_as_windows\fP (arr_in, window_shape, step=1)"
.br
.ti -1c
.RI "def \fBVERSAO_VegaMonitor\&.my_aggregate\&.block_reduce\fP (image, block_size, func=np\&.sum, cval=0)"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VERSAO à partir du code source\&.
