.TH "D:/Mes Donnees/GitHub/VERSAO_P2I/plugin_upload.py" 3 "Mercredi 3 Août 2016" "VERSAO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Mes Donnees/GitHub/VERSAO_P2I/plugin_upload.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI " \fBVERSAO_P2I\&.plugin_upload\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "def \fBVERSAO_P2I\&.plugin_upload\&.main\fP (parameters, arguments)"
.br
.ti -1c
.RI "def \fBVERSAO_P2I\&.plugin_upload\&.hide_password\fP (url, start=6)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBVERSAO_P2I\&.plugin_upload\&.PROTOCOL\fP = 'http'"
.br
.ti -1c
.RI "string \fBVERSAO_P2I\&.plugin_upload\&.SERVER\fP = 'plugins\&.qgis\&.org'"
.br
.ti -1c
.RI "string \fBVERSAO_P2I\&.plugin_upload\&.PORT\fP = '80'"
.br
.ti -1c
.RI "string \fBVERSAO_P2I\&.plugin_upload\&.ENDPOINT\fP = '/plugins/RPC2/'"
.br
.ti -1c
.RI "bool \fBVERSAO_P2I\&.plugin_upload\&.VERBOSE\fP = False"
.br
.ti -1c
.RI "\fBVERSAO_P2I\&.plugin_upload\&.parser\fP = OptionParser(usage='%prog [options] plugin\&.zip')"
.br
.ti -1c
.RI "\fBVERSAO_P2I\&.plugin_upload\&.dest\fP"
.br
.ti -1c
.RI "\fBVERSAO_P2I\&.plugin_upload\&.help\fP"
.br
.ti -1c
.RI "\fBVERSAO_P2I\&.plugin_upload\&.metavar\fP"
.br
.ti -1c
.RI "\fBVERSAO_P2I\&.plugin_upload\&.options\fP"
.br
.ti -1c
.RI "\fBVERSAO_P2I\&.plugin_upload\&.args\fP"
.br
.ti -1c
.RI "\fBVERSAO_P2I\&.plugin_upload\&.server\fP"
.br
.ti -1c
.RI "\fBVERSAO_P2I\&.plugin_upload\&.port\fP"
.br
.ti -1c
.RI "\fBVERSAO_P2I\&.plugin_upload\&.username\fP = getpass\&.getuser()"
.br
.ti -1c
.RI "\fBVERSAO_P2I\&.plugin_upload\&.res\fP = raw_input()"
.br
.ti -1c
.RI "\fBVERSAO_P2I\&.plugin_upload\&.password\fP"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VERSAO à partir du code source\&.
