.TH "D:/Mes Donnees/GitHub/VERSAO_VegaMonitor/TVDI.py" 3 "Jeudi 4 Août 2016" "VERSAO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Mes Donnees/GitHub/VERSAO_VegaMonitor/TVDI.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI " \fBVERSAO_VegaMonitor\&.TVDI\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "def \fBVERSAO_VegaMonitor\&.TVDI\&.TVDI_function\fP (inNDVI, inLST, pas=0\&.02, t=1, s1Min=0\&.3, s2Max=0\&.8, ss1Min=0\&.2, ss2Max=0\&.8)"
.br
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VERSAO à partir du code source\&.
