.TH "VERSAO_VegaMonitor" 3 "Lundi 8 Août 2016" "VERSAO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VERSAO_VegaMonitor \- 
.SH SYNOPSIS
.br
.PP
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI " \fBclass_pretraitement\fP"
.br
.ti -1c
.RI " \fBclip\fP"
.br
.ti -1c
.RI " \fBfunction_data_raster\fP"
.br
.ti -1c
.RI " \fBmetriquePheno\fP"
.br
.ti -1c
.RI " \fBmy_aggregate\fP"
.br
.ti -1c
.RI " \fBplugin_upload\fP"
.br
.ti -1c
.RI " \fBresources\fP"
.br
.ti -1c
.RI " \fBresources_rc\fP"
.br
.ti -1c
.RI " \fBTVDI\fP"
.br
.ti -1c
.RI " \fBVERSAO_VegaMonitor\fP"
.br
.ti -1c
.RI " \fBVERSAO_VegaMonitor_dialog\fP"
.br
.ti -1c
.RI " \fBwh_filter\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "def \fBclassFactory\fP (iface)"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "def VERSAO_VegaMonitor\&.classFactory ( iface)"

.PP
.nf
Load VERSAOVegaMonitor class from file VERSAOVegaMonitor.

:param iface: A QGIS interface instance.
:type iface: QgsInterface

.fi
.PP
 
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VERSAO à partir du code source\&.
