.TH "VERSAO_VegaMonitor.resources" 3 "Jeudi 4 Août 2016" "VERSAO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VERSAO_VegaMonitor.resources \- 
.SH SYNOPSIS
.br
.PP
.SS "Fonctions"

.in +1c
.ti -1c
.RI "def \fBqInitResources\fP ()"
.br
.ti -1c
.RI "def \fBqCleanupResources\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBqt_resource_data\fP"
.br
.ti -1c
.RI "string \fBqt_resource_name\fP"
.br
.ti -1c
.RI "string \fBqt_resource_struct\fP"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "def VERSAO_VegaMonitor\&.resources\&.qCleanupResources ()"

.SS "def VERSAO_VegaMonitor\&.resources\&.qInitResources ()"

.SH "Documentation des variables"
.PP 
.SS "string VERSAO_VegaMonitor\&.resources\&.qt_resource_data"

.SS "string VERSAO_VegaMonitor\&.resources\&.qt_resource_name"
\fBValeur initiale :\fP
.PP
.nf
1 = "\
2 \x00\x07\
3 \x07\x3b\xe0\xb3\
4 \x00\x70\
5 \x00\x6c\x00\x75\x00\x67\x00\x69\x00\x6e\x00\x73\
6 \x00\x14\
7 \x05\x67\x99\x75\
8 \x00\x6d\
9 \x00\x65\x00\x74\x00\x72\x00\x69\x00\x71\x00\x75\x00\x65\x00\x50\x00\x68\x00\x65\x00\x6e\x00\x6f\x00\x6c\x00\x6f\x00\x67\x00\x69\
10 \x00\x71\x00\x75\x00\x65\
11 \x00\x08\
12 \x0a\x61\x5a\xa7\
13 \x00\x69\
14 \x00\x63\x00\x6f\x00\x6e\x00\x2e\x00\x70\x00\x6e\x00\x67\
15 "
.fi
.SS "string VERSAO_VegaMonitor\&.resources\&.qt_resource_struct"
\fBValeur initiale :\fP
.PP
.nf
1 = "\
2 \x00\x00\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x01\
3 \x00\x00\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x02\
4 \x00\x00\x00\x14\x00\x02\x00\x00\x00\x01\x00\x00\x00\x03\
5 \x00\x00\x00\x42\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\
6 "
.fi
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VERSAO à partir du code source\&.
