.TH "VERSAO_VegaMonitor.class_pretraitement.CalculIndicateur" 3 "Jeudi 4 Août 2016" "VERSAO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VERSAO_VegaMonitor.class_pretraitement.CalculIndicateur \- 
.SH SYNOPSIS
.br
.PP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, dlg, iface)"
.br
.ti -1c
.RI "def \fBstop\fP (self)"
.br
.ti -1c
.RI "def \fBdepart\fP (self)"
.br
.ti -1c
.RI "def \fBcumule\fP (self, new)"
.br
.ti -1c
.RI "def \fBcwsi\fP (self)"
.br
.ti -1c
.RI "def \fBtci\fP (self)"
.br
.ti -1c
.RI "def \fBvhi\fP (self)"
.br
.ti -1c
.RI "def \fBtvdi\fP (self)"
.br
.ti -1c
.RI "def \fBsave\fP (self, out, sos, eos, tos, prefixe, progress, GeoTransform, Projection, \fBtci\fP=0)"
.br
.in -1c
.SS "Attributs publics"

.in +1c
.ti -1c
.RI "\fBinterface\fP"
.br
.ti -1c
.RI "\fBqgisInterface\fP"
.br
.ti -1c
.RI "\fBon\fP"
.br
.ti -1c
.RI "\fBok\fP"
.br
.ti -1c
.RI "\fBBar\fP"
.br
.ti -1c
.RI "\fBimageParAn\fP"
.br
.ti -1c
.RI "\fBperiodeTemporelle\fP"
.br
.ti -1c
.RI "\fBdebutSerie\fP"
.br
.ti -1c
.RI "\fBfinSerie\fP"
.br
.ti -1c
.RI "\fBdureeSerie\fP"
.br
.ti -1c
.RI "\fBdebutT\fP"
.br
.ti -1c
.RI "\fBfinT\fP"
.br
.ti -1c
.RI "\fBdureeT\fP"
.br
.ti -1c
.RI "\fBiDebut\fP"
.br
.ti -1c
.RI "\fBiFin\fP"
.br
.ti -1c
.RI "\fBnomPrefixe\fP"
.br
.ti -1c
.RI "\fBlienSave\fP"
.br
.ti -1c
.RI "\fBlienDonnee\fP"
.br
.ti -1c
.RI "\fBfacteureEchelle\fP"
.br
.ti -1c
.RI "\fBcumuleChecked\fP"
.br
.ti -1c
.RI "\fBchecked_multi\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 

.PP
.nf
This class has the tools that allow us to calculate 4 indicators that will allow
 us to obtain information on the evolution of vegetation and climate conditions    

.fi
.PP
 
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "def VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.__init__ ( self,  dlg,  iface)"

.PP
.nf
Constructor.

.fi
.PP
 
.SH "Documentation des fonctions membres"
.PP 
.SS "def VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.cumule ( self,  new)"

.PP
.nf
Allows to preprocess sos, eos et tos           

.fi
.PP
 
.SS "def VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.cwsi ( self)"

.PP
.nf
Allows to  calculate  crop water stress index

.fi
.PP
 
.SS "def VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.depart ( self)"

.PP
.nf
START, disable the validation button and the active progress bar       

.fi
.PP
 
.SS "def VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.save ( self,  out,  sos,  eos,  tos,  prefixe,  progress,  GeoTransform,  Projection,  tci = \fC0\fP)"

.PP
.nf
saves the calculated indicators with the corresponding anomalies        

.fi
.PP
 
.SS "def VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.stop ( self)"

.PP
.nf
STOP, activate the validation button and disable progress bar 

.fi
.PP
 
.SS "def VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.tci ( self)"

.PP
.nf
Allows to calculate the TCI (temperature conditions index)  

.fi
.PP
 
.SS "def VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.tvdi ( self)"

.PP
.nf
Allows to calculate the TVDI (temperature-vegetation dryness index)

.fi
.PP
 
.SS "def VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.vhi ( self)"

.PP
.nf
Allows to calculate  the VHI (vegetation health index)

.fi
.PP
 
.SH "Documentation des données membres"
.PP 
.SS "VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.Bar"

.SS "VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.checked_multi"

.SS "VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.cumuleChecked"

.SS "VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.debutSerie"

.SS "VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.debutT"

.SS "VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.dureeSerie"

.SS "VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.dureeT"

.SS "VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.facteureEchelle"

.SS "VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.finSerie"

.SS "VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.finT"

.SS "VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.iDebut"

.SS "VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.iFin"

.SS "VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.imageParAn"

.SS "VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.interface"

.SS "VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.lienDonnee"

.SS "VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.lienSave"

.SS "VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.nomPrefixe"

.SS "VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.ok"

.SS "VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.on"

.SS "VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.periodeTemporelle"

.SS "VERSAO_VegaMonitor\&.class_pretraitement\&.CalculIndicateur\&.qgisInterface"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VERSAO à partir du code source\&.
