.TH "VERSAO_P2I.plugin_upload" 3 "Jeudi 30 Juin 2016" "VERSAO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VERSAO_P2I.plugin_upload \- 
.SH SYNOPSIS
.br
.PP
.SS "Fonctions"

.in +1c
.ti -1c
.RI "def \fBmain\fP (parameters, arguments)"
.br
.ti -1c
.RI "def \fBhide_password\fP (url, start=6)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBPROTOCOL\fP = 'http'"
.br
.ti -1c
.RI "string \fBSERVER\fP = 'plugins\&.qgis\&.org'"
.br
.ti -1c
.RI "string \fBPORT\fP = '80'"
.br
.ti -1c
.RI "string \fBENDPOINT\fP = '/plugins/RPC2/'"
.br
.ti -1c
.RI "bool \fBVERBOSE\fP = False"
.br
.ti -1c
.RI "\fBparser\fP = OptionParser(usage='%prog [\fBoptions\fP] plugin\&.zip')"
.br
.ti -1c
.RI "\fBdest\fP"
.br
.ti -1c
.RI "\fBhelp\fP"
.br
.ti -1c
.RI "\fBmetavar\fP"
.br
.ti -1c
.RI "\fBoptions\fP"
.br
.ti -1c
.RI "\fBargs\fP"
.br
.ti -1c
.RI "\fBserver\fP"
.br
.ti -1c
.RI "\fBport\fP"
.br
.ti -1c
.RI "\fBusername\fP = getpass\&.getuser()"
.br
.ti -1c
.RI "\fBres\fP = raw_input()"
.br
.ti -1c
.RI "\fBpassword\fP"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "def VERSAO_P2I\&.plugin_upload\&.hide_password ( url,  start = \fC6\fP)"

.PP
.nf
Returns the http url with password part replaced with '*'.

:param url: URL to upload the plugin to.
:type url: str

:param start: Position of start of password.
:type start: int

.fi
.PP
 
.PP
Définition à la ligne 55 du fichier plugin_upload\&.py\&.
.SS "def VERSAO_P2I\&.plugin_upload\&.main ( parameters,  arguments)"

.PP
.nf
Main entry point.

:param parameters: Command line parameters.
:param arguments: Command line arguments.

.fi
.PP
 
.PP
Définition à la ligne 21 du fichier plugin_upload\&.py\&.
.PP
Références VERSAO_P2I\&.plugin_upload\&.hide_password()\&.
.SH "Documentation des variables"
.PP 
.SS "VERSAO_P2I\&.plugin_upload\&.args"

.PP
Définition à la ligne 86 du fichier plugin_upload\&.py\&.
.SS "VERSAO_P2I\&.plugin_upload\&.dest"

.PP
Définition à la ligne 75 du fichier plugin_upload\&.py\&.
.SS "string VERSAO_P2I\&.plugin_upload\&.ENDPOINT = '/plugins/RPC2/'"

.PP
Définition à la ligne 17 du fichier plugin_upload\&.py\&.
.SS "VERSAO_P2I\&.plugin_upload\&.help"

.PP
Définition à la ligne 76 du fichier plugin_upload\&.py\&.
.SS "VERSAO_P2I\&.plugin_upload\&.metavar"

.PP
Définition à la ligne 76 du fichier plugin_upload\&.py\&.
.SS "VERSAO_P2I\&.plugin_upload\&.options"

.PP
Définition à la ligne 86 du fichier plugin_upload\&.py\&.
.SS "VERSAO_P2I\&.plugin_upload\&.parser = OptionParser(usage='%prog [\fBoptions\fP] plugin\&.zip')"

.PP
Définition à la ligne 73 du fichier plugin_upload\&.py\&.
.SS "VERSAO_P2I\&.plugin_upload\&.password"

.PP
Définition à la ligne 106 du fichier plugin_upload\&.py\&.
.SS "string VERSAO_P2I\&.plugin_upload\&.PORT = '80'"

.PP
Définition à la ligne 16 du fichier plugin_upload\&.py\&.
.SS "VERSAO_P2I\&.plugin_upload\&.port"

.PP
Définition à la ligne 94 du fichier plugin_upload\&.py\&.
.SS "string VERSAO_P2I\&.plugin_upload\&.PROTOCOL = 'http'"

.PP
Définition à la ligne 14 du fichier plugin_upload\&.py\&.
.SS "VERSAO_P2I\&.plugin_upload\&.res = raw_input()"

.PP
Définition à la ligne 99 du fichier plugin_upload\&.py\&.
.SS "string VERSAO_P2I\&.plugin_upload\&.SERVER = 'plugins\&.qgis\&.org'"

.PP
Définition à la ligne 15 du fichier plugin_upload\&.py\&.
.SS "VERSAO_P2I\&.plugin_upload\&.server"

.PP
Définition à la ligne 92 du fichier plugin_upload\&.py\&.
.SS "VERSAO_P2I\&.plugin_upload\&.username = getpass\&.getuser()"

.PP
Définition à la ligne 97 du fichier plugin_upload\&.py\&.
.SS "bool VERSAO_P2I\&.plugin_upload\&.VERBOSE = False"

.PP
Définition à la ligne 18 du fichier plugin_upload\&.py\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VERSAO à partir du code source\&.
