.TH "VERSAO_P2I" 3 "Jeudi 30 Juin 2016" "VERSAO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VERSAO_P2I \- 
.SH SYNOPSIS
.br
.PP
.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI " \fBclass_pretraitement\fP"
.br
.ti -1c
.RI " \fBclip\fP"
.br
.ti -1c
.RI " \fBfunction_data_raster\fP"
.br
.ti -1c
.RI " \fBmetrique_phenologique\fP"
.br
.ti -1c
.RI " \fBmetrique_phenologique_dialog\fP"
.br
.ti -1c
.RI " \fBmetriquePheno\fP"
.br
.ti -1c
.RI " \fBmy_aggregate\fP"
.br
.ti -1c
.RI " \fBplugin_upload\fP"
.br
.ti -1c
.RI " \fBresources\fP"
.br
.ti -1c
.RI " \fBresources_rc\fP"
.br
.ti -1c
.RI " \fBTVDI\fP"
.br
.ti -1c
.RI " \fBwh_filter\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "def \fBclassFactory\fP (iface)"
.br
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "def VERSAO_P2I\&.classFactory ( iface)"

.PP
.nf
Load metriquePhenologique class from file metriquePhenologique.

:param iface: A QGIS interface instance.
:type iface: QgsInterface

.fi
.PP
 
.PP
Définition à la ligne 27 du fichier __init__\&.py\&.
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour VERSAO à partir du code source\&.
